In [1]:
import os
from os.path import isfile, join

import numpy as np

from tqdm import tqdm

from pprint import pprint
import plotly as py
import plotly.graph_objects as go

os.chdir('../')
if not os.path.exists('visualisations'):
    os.mkdir('visualisations')

visualisations_dir = os.getcwd() + '\\Visualisations'
print(f'Saving to visualisations dir: {visualisations_dir}')
from Logistic_Map_Generator import LogisticMapGenerator

Saving to visualisations dir: C:\Users\subst\Projects\GitBase\Logistic-Map-Generator\Visualisations


In [2]:
def makeAxis(title, tickangle):
    return {
      'title': title,
      'titlefont': { 'size': 16 },
      'tickangle': tickangle,
      'tickfont': { 'size': 12 },
      'tickcolor': 'rgba(0,0,0,0)',
      'ticklen': 50,
      'showline': True,
      'showgrid': True
    }

In [3]:
output_file = visualisations_dir + '\\Ternary Plot [t=0, t=+1, t=+2] of Logistic Map.html'

In [4]:
# Create figure
fig = go.Figure()

keys = ['x @ t = 0', 'x @ t = +1', 'x @ t = +2']
total_itts = 100

for idx, r_val in tqdm(enumerate(np.linspace(start=3.0, stop=4.0, num=total_itts, endpoint=False)), total=total_itts):
    
    x=np.random.rand()
    map_gen = LogisticMapGenerator(x=x, r=r_val, alphabet='ABCD', depth=6, ret_type='ternary', ret_history=3)
    
    rawData = [{key:val for key,val in zip(keys, next(map_gen))} for _ in range(10000)]
    
    fig.add_trace(go.Scatterternary({'mode': 'markers',
                                     'a': [i for i in map(lambda x: x['x @ t = 0'], rawData)],
                                     'b': [i for i in map(lambda x: x['x @ t = +1'], rawData)],
                                     'c': [i for i in map(lambda x: x['x @ t = +2'], rawData)],
                                     'name': r_val,
                                     'marker': {'symbol': 100,
                                                'color': '#DB7365',
                                                'size':2,
                                                'line': { 'width': 1 }
                                               }
                                    }
                                   )
                 )

# Make 0th trace visible
fig.data[0].visible = True

# Create and add slider
steps = []
for i in range(len(fig.data)):
    step = dict(
        method="restyle",
        args=["visible", [False] * len(fig.data)],
    )
    #step["args"][1][i] = True  # Toggle i'th trace to "visible"
    steps.append(step)

sliders = [dict(
    active=0,
    currentvalue={"prefix": "r-value: "},
    pad={"t": 50},
    steps=steps
)]

fig.update_layout({
    'ternary': {
        'sum': 1,
        'aaxis': makeAxis('x @ t = 0', 0),
        'baxis': makeAxis('x @ t = +1', 0),
        'caxis': makeAxis('x @ t = +2', 0)
    },
    'annotations': [{
      'showarrow': False,
      'text': 'Simple Ternary Plot with Markers',
        'x': 0.5,
        'y': 1.3,
        'font': { 'size': 15 }
    }],
    'autosize':False,
    'showlegend':False,
    'width':980,
    'height':980,
    'margin':go.layout.Margin(
        l=80,
        r=80,
        b=0,
        t=0,
        pad=0
    ),
    'paper_bgcolor':'rgba(0,0,0,1.0)',
    'plot_bgcolor':'rgba(0,0,0,1.0)',
    'sliders':sliders
})

fig.update_layout(
    sliders=sliders
)

py.offline.plot(fig, filename=output_file,auto_open=False)

  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

[0.33388823 0.33222359 0.33388819]


  1%|▊                                                                                 | 1/100 [00:07<13:09,  7.97s/it]

[0.32204823 0.35590353 0.32204823]


  2%|█▋                                                                                | 2/100 [00:16<13:07,  8.04s/it]

[0.34864762 0.30270476 0.34864762]


  3%|██▍                                                                               | 3/100 [00:24<12:55,  8.00s/it]

[0.35197057 0.29605886 0.35197057]


  4%|███▎                                                                              | 4/100 [00:32<12:52,  8.05s/it]

[0.31046283 0.37907434 0.31046283]


  5%|████                                                                              | 5/100 [00:40<12:46,  8.07s/it]

[0.30769231 0.38461538 0.30769231]


  6%|████▉                                                                             | 6/100 [00:48<12:34,  8.02s/it]

[0.35929597 0.28140806 0.35929597]


  7%|█████▋                                                                            | 7/100 [00:56<12:28,  8.05s/it]

[0.36125603 0.27748794 0.36125603]


  8%|██████▌                                                                           | 8/100 [01:04<12:13,  7.97s/it]

[0.30069245 0.3986151  0.30069245]


  9%|███████▍                                                                          | 9/100 [01:11<11:55,  7.87s/it]

[0.36474469 0.27051063 0.36474469]


 10%|████████                                                                         | 10/100 [01:19<11:44,  7.83s/it]

[0.29672215 0.4065557  0.29672215]


 11%|████████▉                                                                        | 11/100 [01:27<11:27,  7.73s/it]

[0.36780823 0.26438353 0.36780823]


 12%|█████████▋                                                                       | 12/100 [01:35<11:37,  7.93s/it]

[0.36921731 0.26156539 0.36921731]


 13%|██████████▌                                                                      | 13/100 [01:43<11:30,  7.94s/it]

[0.29142902 0.41714197 0.29142902]


 14%|███████████▎                                                                     | 14/100 [01:50<11:12,  7.82s/it]

[0.37183807 0.25632385 0.37183807]


 15%|████████████▏                                                                    | 15/100 [01:58<10:58,  7.74s/it]

[0.3730638 0.2538724 0.3730638]


 16%|████████████▉                                                                    | 16/100 [02:06<10:49,  7.73s/it]

[0.37424051 0.25151898 0.37424051]


 17%|█████████████▊                                                                   | 17/100 [02:13<10:41,  7.73s/it]

[0.3753727 0.2492546 0.3753727]


 18%|██████████████▌                                                                  | 18/100 [02:21<10:27,  7.65s/it]

[0.37646421 0.24707159 0.37646421]


 19%|███████████████▍                                                                 | 19/100 [02:29<10:19,  7.65s/it]

[0.37751836 0.24496329 0.37751836]


 20%|████████████████▏                                                                | 20/100 [02:36<10:10,  7.63s/it]

[0.37853804 0.24292392 0.37853804]


 21%|█████████████████                                                                | 21/100 [02:44<10:14,  7.78s/it]

[0.37952579 0.24094842 0.37952579]


 22%|█████████████████▊                                                               | 22/100 [02:52<10:05,  7.76s/it]

[0.27841445 0.4431711  0.27841445]


 23%|██████████████████▋                                                              | 23/100 [03:00<10:00,  7.80s/it]

[0.38141421 0.23717157 0.38141421]


 24%|███████████████████▍                                                             | 24/100 [03:07<09:47,  7.73s/it]

[0.2759092  0.44818161 0.2759092 ]


 25%|████████████████████▎                                                            | 25/100 [03:15<09:28,  7.59s/it]

[0.38319876 0.23360248 0.38319876]


 26%|█████████████████████                                                            | 26/100 [03:22<09:16,  7.52s/it]

[0.27350705 0.4529859  0.27350705]


 27%|█████████████████████▊                                                           | 27/100 [03:29<09:05,  7.47s/it]

[0.2723411 0.4553178 0.2723411]


 28%|██████████████████████▋                                                          | 28/100 [03:37<08:56,  7.45s/it]

[0.27119694 0.45760613 0.27119694]


 29%|███████████████████████▍                                                         | 29/100 [03:45<09:07,  7.71s/it]

[0.27007347 0.45985306 0.27007347]


 30%|████████████████████████▎                                                        | 30/100 [03:53<08:54,  7.64s/it]

[0.2689697  0.46206059 0.2689697 ]


 31%|█████████████████████████                                                        | 31/100 [04:00<08:38,  7.51s/it]

[0.26788472 0.46423055 0.26788472]


 32%|█████████████████████████▉                                                       | 32/100 [04:07<08:28,  7.48s/it]

[0.26681768 0.46636463 0.26681768]


 33%|██████████████████████████▋                                                      | 33/100 [04:14<08:10,  7.32s/it]

[0.3895117 0.2209766 0.3895117]


 34%|███████████████████████████▌                                                     | 34/100 [04:21<08:00,  7.29s/it]

[0.26473436 0.47053128 0.26473436]


 35%|████████████████████████████▎                                                    | 35/100 [04:28<07:50,  7.24s/it]

[0.26371669 0.47256663 0.26371669]


 36%|█████████████████████████████▏                                                   | 36/100 [04:36<07:46,  7.29s/it]

[0.39160683 0.21678634 0.39160683]


 37%|█████████████████████████████▉                                                   | 37/100 [04:43<07:44,  7.38s/it]

[0.39227792 0.21544417 0.39227792]


 38%|██████████████████████████████▊                                                  | 38/100 [04:51<07:37,  7.39s/it]

[0.39293628 0.21412743 0.39293628]


 39%|███████████████████████████████▌                                                 | 39/100 [04:58<07:30,  7.38s/it]

[0.2597918 0.4804164 0.2597918]


 40%|████████████████████████████████▍                                                | 40/100 [05:06<07:31,  7.53s/it]

[0.25884439 0.48231122 0.25884439]


 41%|█████████████████████████████████▏                                               | 41/100 [05:14<07:24,  7.53s/it]

[0.25790957 0.48418086 0.25790957]


 42%|██████████████████████████████████                                               | 42/100 [05:21<07:17,  7.54s/it]

[0.39545212 0.20909576 0.39545212]


 43%|██████████████████████████████████▊                                              | 43/100 [05:28<07:02,  7.42s/it]

[0.39605381 0.20789238 0.39605381]


 44%|███████████████████████████████████▋                                             | 44/100 [05:36<06:54,  7.40s/it]

[0.2551765  0.48964701 0.2551765 ]


 45%|████████████████████████████████████▍                                            | 45/100 [05:43<06:49,  7.45s/it]

[0.25742957 0.49205386 0.25051657]


 46%|█████████████████████████████████████▎                                           | 46/100 [05:51<06:49,  7.59s/it]

[0.40753765 0.19551854 0.39694381]


 47%|██████████████████████████████████████                                           | 47/100 [05:59<06:42,  7.59s/it]

[0.27387359 0.49554482 0.23058158]


 48%|██████████████████████████████████████▉                                          | 48/100 [06:07<06:37,  7.64s/it]

[0.38006361 0.22262347 0.39731292]


 49%|███████████████████████████████████████▋                                         | 49/100 [06:14<06:29,  7.63s/it]

[0.37756843 0.22516115 0.39727043]


 50%|████████████████████████████████████████▌                                        | 50/100 [06:22<06:20,  7.61s/it]

[0.2237868  0.48340883 0.29280437]


 51%|█████████████████████████████████████████▎                                       | 51/100 [06:29<06:06,  7.48s/it]

[0.28761475 0.49798687 0.21439839]


 52%|██████████████████████████████████████████                                       | 52/100 [06:36<05:57,  7.45s/it]

[0.2183744  0.48189617 0.29972942]


 53%|██████████████████████████████████████████▉                                      | 53/100 [06:44<05:50,  7.47s/it]

[0.29256663 0.49875267 0.2086807 ]


 54%|███████████████████████████████████████████▋                                     | 54/100 [06:51<05:46,  7.53s/it]

[0.36862004 0.23445321 0.39692674]


 55%|████████████████████████████████████████████▌                                    | 55/100 [06:59<05:43,  7.64s/it]

[0.43184701 0.17266682 0.39548617]


 56%|█████████████████████████████████████████████▎                                   | 56/100 [07:07<05:30,  7.51s/it]

[0.2041884  0.47334675 0.32246485]


 57%|██████████████████████████████████████████████▏                                  | 57/100 [07:14<05:25,  7.57s/it]

[0.36022326 0.24652783 0.39324891]


 58%|██████████████████████████████████████████████▉                                  | 58/100 [07:22<05:17,  7.56s/it]

[0.26906825 0.52248501 0.20844674]


 59%|███████████████████████████████████████████████▊                                 | 59/100 [07:29<05:11,  7.59s/it]

[0.2691653  0.52497868 0.20585602]


 60%|████████████████████████████████████████████████▌                                | 60/100 [07:37<04:59,  7.50s/it]

[0.19342251 0.46596878 0.34060871]


 61%|█████████████████████████████████████████████████▍                               | 61/100 [07:44<04:53,  7.53s/it]

[0.45052069 0.1586965  0.3907828 ]


 62%|██████████████████████████████████████████████████▏                              | 62/100 [07:52<04:46,  7.53s/it]

[0.44227453 0.16299646 0.39472901]


 63%|███████████████████████████████████████████████████                              | 63/100 [07:59<04:39,  7.55s/it]

[0.3707158  0.22527461 0.4040096 ]


 64%|███████████████████████████████████████████████████▊                             | 64/100 [08:08<04:42,  7.86s/it]

[0.45830346 0.15325446 0.38844208]


 65%|████████████████████████████████████████████████████▋                            | 65/100 [08:16<04:35,  7.88s/it]

[0.33941305 0.29828307 0.36230388]


 66%|█████████████████████████████████████████████████████▍                           | 66/100 [08:23<04:23,  7.75s/it]

[0.16723321 0.43563211 0.39713468]


 67%|██████████████████████████████████████████████████████▎                          | 67/100 [08:31<04:12,  7.65s/it]

[0.43218304 0.16692057 0.40089639]


 68%|███████████████████████████████████████████████████████                          | 68/100 [08:38<04:00,  7.51s/it]

[0.33412297 0.32704839 0.33882864]


 69%|███████████████████████████████████████████████████████▉                         | 69/100 [08:45<03:51,  7.47s/it]

[0.34811253 0.26482343 0.38706404]


 70%|████████████████████████████████████████████████████████▋                        | 70/100 [08:53<03:44,  7.48s/it]

[0.25689966 0.54764936 0.19545098]


 71%|█████████████████████████████████████████████████████████▌                       | 71/100 [09:00<03:33,  7.36s/it]

[0.32904017 0.39891553 0.27204429]


 72%|██████████████████████████████████████████████████████████▎                      | 72/100 [09:07<03:26,  7.37s/it]

[0.31918007 0.5158017  0.16501824]


 73%|███████████████████████████████████████████████████████████▏                     | 73/100 [09:15<03:21,  7.46s/it]

[0.44860094 0.15480344 0.39659562]


 74%|███████████████████████████████████████████████████████████▉                     | 74/100 [09:22<03:12,  7.39s/it]

[0.13169873 0.38050901 0.48779226]


 75%|████████████████████████████████████████████████████████████▊                    | 75/100 [09:30<03:04,  7.39s/it]

[0.38930372 0.19603486 0.41466142]


 76%|█████████████████████████████████████████████████████████████▌                   | 76/100 [09:37<02:54,  7.27s/it]

[0.2925629  0.57405522 0.13338188]


 77%|██████████████████████████████████████████████████████████████▎                  | 77/100 [09:44<02:47,  7.29s/it]

[0.30518816 0.57093216 0.12387968]


 78%|███████████████████████████████████████████████████████████████▏                 | 78/100 [09:52<02:44,  7.47s/it]

[0.20271879 0.50604788 0.29123333]


 79%|███████████████████████████████████████████████████████████████▉                 | 79/100 [09:59<02:33,  7.29s/it]

[0.33438686 0.32134459 0.34426855]


 80%|████████████████████████████████████████████████████████████████▊                | 80/100 [10:07<02:28,  7.43s/it]

[0.32838718 0.52244834 0.14916448]


 81%|█████████████████████████████████████████████████████████████████▌               | 81/100 [10:14<02:22,  7.48s/it]

[0.37445953 0.20872056 0.4168199 ]


 82%|██████████████████████████████████████████████████████████████████▍              | 82/100 [10:21<02:13,  7.44s/it]

[0.36098024 0.22734093 0.41167883]


 83%|███████████████████████████████████████████████████████████████████▏             | 83/100 [10:29<02:06,  7.47s/it]

[0.3118628  0.59164345 0.09649375]


 84%|████████████████████████████████████████████████████████████████████             | 84/100 [10:36<01:58,  7.40s/it]

[0.60083427 0.093563   0.30560273]


 85%|████████████████████████████████████████████████████████████████████▊            | 85/100 [10:44<01:50,  7.37s/it]

[0.61215272 0.09009123 0.29775605]


 86%|█████████████████████████████████████████████████████████████████████▋           | 86/100 [10:51<01:45,  7.53s/it]

[0.32760933 0.578744   0.09364667]


 87%|██████████████████████████████████████████████████████████████████████▍          | 87/100 [10:59<01:37,  7.47s/it]

[0.40173795 0.17882719 0.41943487]


 88%|███████████████████████████████████████████████████████████████████████▎         | 88/100 [11:06<01:28,  7.40s/it]

[0.65576471 0.07762246 0.26661282]


 89%|████████████████████████████████████████████████████████████████████████         | 89/100 [11:13<01:20,  7.31s/it]

[0.12841618 0.38714199 0.48444182]


 90%|████████████████████████████████████████████████████████████████████████▉        | 90/100 [11:21<01:13,  7.38s/it]

[0.33308606 0.36478764 0.3021263 ]


 91%|█████████████████████████████████████████████████████████████████████████▋       | 91/100 [11:28<01:06,  7.42s/it]

[0.33697532 0.29043421 0.37259047]


 92%|██████████████████████████████████████████████████████████████████████████▌      | 92/100 [11:36<00:59,  7.45s/it]

[0.18302365 0.49653614 0.32044021]


 93%|███████████████████████████████████████████████████████████████████████████▎     | 93/100 [11:43<00:50,  7.27s/it]

[0.33708187 0.43458349 0.22833464]


 94%|████████████████████████████████████████████████████████████████████████████▏    | 94/100 [11:50<00:43,  7.28s/it]

[0.50219839 0.12346998 0.37433163]


 95%|████████████████████████████████████████████████████████████████████████████▉    | 95/100 [11:57<00:36,  7.39s/it]

[0.34434095 0.55709852 0.09856054]


 96%|█████████████████████████████████████████████████████████████████████████████▊   | 96/100 [12:05<00:29,  7.33s/it]

[0.33431538 0.30925736 0.35642725]


 97%|██████████████████████████████████████████████████████████████████████████████▌  | 97/100 [12:13<00:22,  7.61s/it]

[0.33366304 0.35928885 0.3070481 ]


 98%|███████████████████████████████████████████████████████████████████████████████▍ | 98/100 [12:20<00:15,  7.58s/it]

[0.11482286 0.3647064  0.52047074]


 99%|████████████████████████████████████████████████████████████████████████████████▏| 99/100 [12:28<00:07,  7.48s/it]

[0.19356695 0.52612495 0.28030811]


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [12:35<00:00,  7.56s/it]


'C:\\Users\\subst\\Projects\\GitBase\\Logistic-Map-Generator\\Visualisations\\Ternary Plot [t=0, t=+1, t=+2] of Logistic Map.html'